# Generated by Django 3.2 on 2021-04-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_profanity_check', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
